---
- name: Install pip for Python 2.7 from RHEL
  yum:
    name: 'python2-pip'
    state: present

# Pygments for system wide syntax highlighting with 'ccat' command
- name: Install Pygments for Python 3.5
  pip:
    name: Pygments

- name: Set 'ccat' alias in global bashrc
  lineinfile:
    dest: /etc/bashrc
    line: "{{ item.line }}"
  with_items:
    - { line: '# The line below allows syntax highlighting for files with the command "ccat".' }
    - { line: "alias ccat='pygmentize -O style=monokai -f terminal -g'" }

# Set up virtualenvwrapper to use Python 3.5 by default
- name: Install virtualenvwrapper for Python 3.5
  pip:
    name: virtualenvwrapper

- name: Set virtualenvwrapper in global bashrc
  lineinfile:
    dest: /etc/bashrc
    line: "{{ item.line }}"
  with_items:
    - { line: '# virtualenvwrapper Setup' }
    - { line: 'export VIRTUALENV_PYTHON=/usr/bin/python3.5' }
    - { line: 'source /usr/bin/virtualenvwrapper.sh' }
