---
- name: Configure vagrant box
  hosts: all
  become: yes
  roles:
    - { role: vagrant_configure, tags: ['setup'] }
    - { role: firewalld, tags: ['firewalld'] }
    - { role: repository_epel, tags: ['yum'] }
    - { role: repository_ius, tags: ['yum'] }
    - { role: yum_packages, tags: ['yum'] }
    - { role: wkhtmltopdf, tags: ['yum', 'pdf'] }
    - { role: python27, tags: ['python'] }
    - { role: python36, tags: ['python'] }
    - { role: freetds, tags: ['sql', 'sql server', 'freetds'] }
    - { role: mssql, tags: ['sql', 'sql server', 'msodbc'] }
    - { role: postgresql, tags: ['postgresql']}
    - { role: postgresql_vagrant, tags: ['postgresql']}

    ######################################################
    # These roles may be added at the user's discretion  #
    # They are not necessarily required for development. #
    ######################################################

    # - { role: elastic_search, tags: ['search', 'elastic'] }
    # - { role: redis, tags: ['cache', 'redis'] }
    # - { role: httpd, tags: ['httpd'] }
    # - { role: httpd_mod_wsgi, tags: ['python', 'httpd'] }
    # - { role: ldap, tags: ['ldap'] }

    ################################################
    # NodeJS can be added as well, but is best run #
    # locally on the machine.                      #
    ################################################

    # - { role: nodejs, tags: ['nodejs', 'npm']}

    #################################################
    # The following line will perform a yum update. #
    # This would take a while!                      #
    #################################################

    # - { role: yum_update, tags: ['yum'] }
